:m +Control.Exception

([r| plot() |] >> return ()) `Control.Exception.catch` (\(H.RError x) -> putStrLn x)

([r| plot( |] >> return ()) `Control.Exception.catch` (\(H.RError x) -> putStrLn x)

([r| 1+()-2 |] >> return ()) `Control.Exception.catch` (\(H.RError x) -> putStrLn x)
