:m +Control.Exception

(Control.Exception.evaluate [r| plot() |] >> return ()) `Control.Exception.catch` (\(H.RError x) -> putStrLn x)

(Control.Exception.evaluate [r| plot( |] >> return ()) `Control.Exception.catch` (\(H.RError x) -> putStrLn x)

(Control.Exception.evaluate [r| 1+()-2 |] >> return ()) `Control.Exception.catch` (\(H.RError x) -> putStrLn x)
